version: '3.8'
services:
  proxy:
    image: nginx:1.21
    restart: on-failure
    ports:
      - 127.0.0.1:443:443
    secrets:
      - proxy_certificate_and_int_cas.pem
      - proxy_certificate_private_key.pem
      - proxy_trusted_client_cas.pem
    volumes:
      - type: bind
        source: ./proxy/conf.d
        target: /etc/nginx/conf.d
        read_only: true
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    networks:
      dic-fhir-frontend:
        ipv4_address: 172.20.0.66
      cos-fhir-frontend:
        ipv4_address: 172.20.0.82
      internet:
        aliases:
          - dic
          - cos
    environment:
      TZ: Europe/Berlin


  db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      TZ: Europe/Berlin
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: postgres
    networks:
      - dic-fhir-backend
      - cos-fhir-backend
      - dic-bpe-backend
      - cos-bpe-backend
    secrets:
      - db_liquibase.password
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./db/init-db.sh
        target: /docker-entrypoint-initdb.d/init-db.sh
        read_only: true


  dic-fhir:
    image: ghcr.io/highmed/fhir:0.6.0-RC1
    restart: on-failure
    ports:
      - 127.0.0.1:5000:5000
    secrets:
      - db_liquibase.password
      - db_dic_fhir_user.password
      - db_dic_fhir_user_permanent_delete.password
      - app_client_trust_certificates.pem
      - app_dic_client_certificate.pem
      - app_dic_client_certificate_private_key.pem
      - app_client_certificate_private_key.pem.password
    volumes:
      - type: bind
        source: ./dic/fhir/conf/bundle.xml
        target: /opt/fhir/conf/bundle.xml
      - type: bind
        source: ./dic/fhir/log
        target: /opt/fhir/log
    environment:
      TZ: Europe/Berlin
      EXTRA_JVM_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000
      ORG_HIGHMED_DSF_FHIR_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      ORG_HIGHMED_DSF_FHIR_DB_USER_PASSWORD_FILE: /run/secrets/db_dic_fhir_user.password
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_PASSWORD_FILE: /run/secrets/db_dic_fhir_user_permanent_delete.password
      ORG_HIGHMED_DSF_FHIR_CLIENT_TRUST_CERTIFICATES: /run/secrets/app_client_trust_certificates.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_dic_client_certificate.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_dic_client_certificate_private_key.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      ORG_HIGHMED_DSF_FHIR_DB_URL: jdbc:postgresql://db/dic_fhir
      ORG_HIGHMED_DSF_FHIR_DB_USER_GROUP: dic_fhir_users
      ORG_HIGHMED_DSF_FHIR_DB_USER_USERNAME: dic_fhir_server_user
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_GROUP: dic_fhir_permanent_delete_users
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_USERNAME: dic_fhir_server_permanent_delete_user
      ORG_HIGHMED_DSF_FHIR_SERVER_BASE_URL: https://dic/fhir
      ORG_HIGHMED_DSF_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: Test_DIC
      ORG_HIGHMED_DSF_FHIR_SERVER_USER_THUMBPRINTS: ${DIC_USER_THUMBPRINTS}
      ORG_HIGHMED_DSF_FHIR_SERVER_USER_THUMBPRINTS_PERMANENT_DELETE: ${DIC_USER_THUMBPRINTS_PERMANENT_DELETE}
    networks:
      dic-fhir-frontend:
        ipv4_address: 172.20.0.67
      dic-fhir-backend:
      internet:
    depends_on:
      - db
      - proxy
  dic-bpe:
    image: ghcr.io/highmed/bpe:0.6.0-RC1
    restart: on-failure
    ports:
      - 127.0.0.1:5003:5003
    secrets:
      - db_liquibase.password
      - db_dic_bpe_user.password
      - db_dic_bpe_user_camunda.password
      - app_client_trust_certificates.pem
      - app_dic_client_certificate.pem
      - app_dic_client_certificate_private_key.pem
      - app_client_certificate_private_key.pem.password
      - cos_public_key.pem
    volumes:
      - type: bind
        source: ./dic/bpe/plugin
        target: /opt/bpe/plugin
        read_only: true
      - type: bind
        source: ./dic/bpe/process
        target: /opt/bpe/process
        read_only: true
      - type: bind
        source: ./dic/bpe/log
        target: /opt/bpe/log
      - type: bind
        source: ./dic/bpe/last_event
        target: /opt/bpe/last_event
    environment:
      TZ: Europe/Berlin
      EXTRA_JVM_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5003
      ORG_HIGHMED_DSF_BPE_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      ORG_HIGHMED_DSF_BPE_DB_USER_PASSWORD_FILE: /run/secrets/db_dic_bpe_user.password
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_PASSWORD_FILE: /run/secrets/db_dic_bpe_user_camunda.password
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_TRUST_CERTIFICATES: /run/secrets/app_client_trust_certificates.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_dic_client_certificate.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_dic_client_certificate_private_key.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      ORG_HIGHMED_DSF_BPE_DB_URL: jdbc:postgresql://db/dic_bpe
      ORG_HIGHMED_DSF_BPE_DB_USER_GROUP: dic_bpe_users
      ORG_HIGHMED_DSF_BPE_DB_USER_USERNAME: dic_bpe_server_user
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_GROUP: dic_camunda_users
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_USERNAME: dic_camunda_server_user
      ORG_HIGHMED_DSF_BPE_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: Test_DIC
      ORG_HIGHMED_DSF_BPE_FHIR_SERVER_BASE_URL: https://dic/fhir
      ORG_HIGHMED_DSF_BPE_PROCESS_EXCLUDED: medizininformatik-initiativede_dataReceive/0.2.0
      DE_MEDIZININFORMATIK_INITIATIVE_KDS_FHIR_SERVER_BASE_URL: http://dic-fhir-store:8080/fhir
    networks:
      dic-bpe-frontend:
      dic-bpe-backend:
      internet:
    depends_on:
      - db
      - dic-fhir
    # - dic-fhir-store not defining a dependency here, dic-fhir-store* needs to be started manually
  dic-fhir-store-hapi:
    build: ./dic/hapi
    restart: on-failure
    ports:
      - 127.0.0.1:8080:8080
    environment:
      TZ: Europe/Berlin
    networks:
      dic-bpe-backend:
        aliases:
          - dic-fhir-store


  cos-fhir:
    image: ghcr.io/highmed/fhir:0.6.0-RC1
    restart: on-failure
    ports:
      - 127.0.0.1:5001:5001
    secrets:
      - db_liquibase.password
      - db_cos_fhir_user.password
      - db_cos_fhir_user_permanent_delete.password
      - app_client_trust_certificates.pem
      - app_cos_client_certificate.pem
      - app_cos_client_certificate_private_key.pem
      - app_client_certificate_private_key.pem.password
    volumes:
      - type: bind
        source: ./cos/fhir/conf/bundle.xml
        target: /opt/fhir/conf/bundle.xml
      - type: bind
        source: ./cos/fhir/log
        target: /opt/fhir/log
    environment:
      TZ: Europe/Berlin
      EXTRA_JVM_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5001
      ORG_HIGHMED_DSF_FHIR_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      ORG_HIGHMED_DSF_FHIR_DB_USER_PASSWORD_FILE: /run/secrets/db_cos_fhir_user.password
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_PASSWORD_FILE: /run/secrets/db_cos_fhir_user_permanent_delete.password
      ORG_HIGHMED_DSF_FHIR_CLIENT_TRUST_CERTIFICATES: /run/secrets/app_client_trust_certificates.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_cos_client_certificate.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_cos_client_certificate_private_key.pem
      ORG_HIGHMED_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      ORG_HIGHMED_DSF_FHIR_DB_URL: jdbc:postgresql://db/cos_fhir
      ORG_HIGHMED_DSF_FHIR_DB_USER_GROUP: cos_fhir_users
      ORG_HIGHMED_DSF_FHIR_DB_USER_USERNAME: cos_fhir_server_user
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_GROUP: cos_fhir_permanent_delete_users
      ORG_HIGHMED_DSF_FHIR_DB_USER_PERMANENT_DELETE_USERNAME: cos_fhir_server_permanent_delete_user
      ORG_HIGHMED_DSF_FHIR_SERVER_BASE_URL: https://cos/fhir
      ORG_HIGHMED_DSF_FHIR_SERVER_USER_THUMBPRINTS: ${COS_USER_THUMBPRINTS}
      ORG_HIGHMED_DSF_FHIR_SERVER_USER_THUMBPRINTS_PERMANENT_DELETE: ${COS_USER_THUMBPRINTS_PERMANENT_DELETE}
      ORG_HIGHMED_DSF_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: Test_COS
    networks:
      cos-fhir-frontend:
        ipv4_address: 172.20.0.83
      cos-fhir-backend:
      internet:
    depends_on:
      - db
      - proxy
  cos-bpe:
    image: ghcr.io/highmed/bpe:0.6.0-RC1
    restart: on-failure
    ports:
      - 127.0.0.1:5004:5004
    secrets:
      - db_liquibase.password
      - db_cos_bpe_user.password
      - db_cos_bpe_user_camunda.password
      - app_client_trust_certificates.pem
      - app_cos_client_certificate.pem
      - app_cos_client_certificate_private_key.pem
      - app_client_certificate_private_key.pem.password
      - cos_private_key.pem
      - cos_public_key.pem
    volumes:
      - type: bind
        source: ./cos/bpe/plugin
        target: /opt/bpe/plugin
        read_only: true
      - type: bind
        source: ./cos/bpe/process
        target: /opt/bpe/process
        read_only: true
      - type: bind
        source: ./cos/bpe/log
        target: /opt/bpe/log
      - type: bind
        source: ./cos/bpe/last_event
        target: /opt/bpe/last_event
    environment:
      TZ: Europe/Berlin
      EXTRA_JVM_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5004
      ORG_HIGHMED_DSF_BPE_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      ORG_HIGHMED_DSF_BPE_DB_USER_PASSWORD_FILE: /run/secrets/db_cos_bpe_user.password
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_PASSWORD_FILE: /run/secrets/db_cos_bpe_user_camunda.password
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_TRUST_CERTIFICATES: /run/secrets/app_client_trust_certificates.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_cos_client_certificate.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_cos_client_certificate_private_key.pem
      ORG_HIGHMED_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      ORG_HIGHMED_DSF_BPE_DB_URL: jdbc:postgresql://db/cos_bpe
      ORG_HIGHMED_DSF_BPE_DB_USER_GROUP: cos_bpe_users
      ORG_HIGHMED_DSF_BPE_DB_USER_USERNAME: cos_bpe_server_user
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_GROUP: cos_camunda_users
      ORG_HIGHMED_DSF_BPE_DB_USER_CAMUNDA_USERNAME: cos_camunda_server_user
      ORG_HIGHMED_DSF_BPE_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: Test_COS
      ORG_HIGHMED_DSF_BPE_FHIR_SERVER_BASE_URL: https://cos/fhir
      ORG_HIGHMED_DSF_BPE_PROCESS_EXCLUDED: medizininformatik-initiativede_dataSend/0.2.0
      DE_MEDIZININFORMATIK_INITIATIVE_KDS_FHIR_SERVER_BASE_URL: http://cos-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_COS_PRIVATE_KEY: /run/secrets/cos_private_key.pem
      DE_MEDIZININFORMATIK_INITIATIVE_COS_PUBLIC_KEY: /run/secrets/cos_public_key.pem
    networks:
      cos-bpe-frontend:
      cos-bpe-backend:
      internet:
    depends_on:
      - db
      - cos-fhir
      # - cos-fhir-store not defining a dependency here, cos-fhir-store* needs to be started manually
  cos-fhir-store-hapi:
    build: ./cos/hapi
    restart: on-failure
    ports:
      - 127.0.0.1:8081:8080
    environment:
      TZ: Europe/Berlin
    networks:
      cos-bpe-backend:
        aliases:
          - cos-fhir-store


secrets:
  proxy_certificate_and_int_cas.pem:
    file: ./secrets/proxy_certificate_and_int_cas.pem
  proxy_certificate_private_key.pem:
    file: ./secrets/proxy_certificate_private_key.pem
  proxy_trusted_client_cas.pem:
    file: ./secrets/proxy_trusted_client_cas.pem

  db_liquibase.password:
    file: ./secrets/db_liquibase.password
    
  db_dic_fhir_user.password:
    file: ./secrets/db_dic_fhir_user.password
  db_dic_fhir_user_permanent_delete.password:
    file: ./secrets/db_dic_fhir_user_permanent_delete.password
  db_dic_bpe_user.password:
    file: ./secrets/db_dic_bpe_user.password
  db_dic_bpe_user_camunda.password:
    file: ./secrets/db_dic_bpe_user_camunda.password

  db_cos_fhir_user.password:
    file: ./secrets/db_cos_fhir_user.password
  db_cos_fhir_user_permanent_delete.password:
    file: ./secrets/db_cos_fhir_user_permanent_delete.password
  db_cos_bpe_user.password:
    file: ./secrets/db_cos_bpe_user.password
  db_cos_bpe_user_camunda.password:
    file: ./secrets/db_cos_bpe_user_camunda.password

  app_client_trust_certificates.pem:
    file: ./secrets/app_client_trust_certificates.pem
  app_client_certificate_private_key.pem.password:
    file: ./secrets/app_client_certificate_private_key.pem.password

  app_dic_client_certificate.pem:
    file: ./secrets/app_dic_client_certificate.pem
  app_dic_client_certificate_private_key.pem:
    file: ./secrets/app_dic_client_certificate_private_key.pem

  app_cos_client_certificate.pem:
    file: ./secrets/app_cos_client_certificate.pem
  app_cos_client_certificate_private_key.pem:
    file: ./secrets/app_cos_client_certificate_private_key.pem

  cos_private_key.pem:
    file: ./secrets/cos_private_key.pem
  cos_public_key.pem:
    file: ./secrets/cos_public_key.pem

networks:
  internet:
  dic-fhir-frontend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.64/28
  dic-fhir-backend:
  dic-bpe-frontend:
  dic-bpe-backend:
  cos-fhir-frontend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.80/28
  cos-fhir-backend:
  cos-bpe-frontend:
  cos-bpe-backend:


volumes:
  db-data:
    name: db-data-mii-dsf-processes